// <auto-generated />
namespace UI.Business.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_TBL_CHAMADOS_DataInicio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_TBL_CHAMADOS_DataInicio));
        
        string IMigrationMetadata.Id
        {
            get { return "201811231238393_add_TBL_CHAMADOS_DataInicio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
